# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0e8064c28bd244d1a89836d9de7c1a1fdec8bdc71c37a9fb1bd689b0cd900c65930774a3c3dc7f62ac900728a71d1412e4f33fc1b650bc32487eca25504a757

test:
  secret_key_base: 3b102c6d9e9a4f06c421fd9a972fd76e607f86e80675222e7bf9036b98025b4251985173a0d1e07d3021b0e7d755dd95fdaf0ad93f60e7452cb0c64c05ba66af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
